from django.urls import path

from .views import (
    customer_create, customer_detail, customer_edit, customer_interaction_create, customer_list,
    dashboard,
    enquiry_create, enquiry_edit, enquiry_list,
    order_create, order_detail, order_edit, order_list, order_pdf,
    quotation_create, quotation_detail, quotation_edit, quotation_list, quotation_pdf,
    customer_login, customer_register, manager_notifications, manager_request_review,
    manager_requests, portal_dashboard, portal_request_create, portal_request_detail, portal_requests,
    portal_quotations, portal_quotation_detail, portal_quotation_response, portal_design_response,
    confirm_quotation_order, create_design, design_history, payment_create, delivery_update, portal_orders, portal_order_detail, portal_feedback,
)

app_name = "sales"

urlpatterns = [
    path("", dashboard, name="dashboard"),
    path("portal/login/", customer_login, name="portal_login"),
    path("portal/register/", customer_register, name="portal_register"),
    path("portal/", portal_dashboard, name="portal_dashboard"),
    path("portal/requests/", portal_requests, name="portal_requests"),
    path("portal/requests/new/", portal_request_create, name="portal_request_create"),
    path("portal/requests/<int:pk>/", portal_request_detail, name="portal_request_detail"),
    path("portal/quotations/", portal_quotations, name="portal_quotations"),
    path("portal/quotations/<int:pk>/", portal_quotation_detail, name="portal_quotation_detail"),
    path("portal/quotations/<int:pk>/response/", portal_quotation_response, name="portal_quotation_response"),
    path("portal/designs/<int:pk>/response/", portal_design_response, name="portal_design_response"),
    path("portal/orders/", portal_orders, name="portal_orders"),
    path("portal/orders/<int:pk>/", portal_order_detail, name="portal_order_detail"),
    path("portal/orders/<int:pk>/feedback/", portal_feedback, name="portal_feedback"),
    path("requests/", manager_requests, name="manager_requests"),
    path("requests/<int:pk>/", manager_request_review, name="manager_request_review"),
    path("quotations/<int:pk>/confirm-order/", confirm_quotation_order, name="confirm_quotation_order"),
    path("quotations/<int:pk>/design/", create_design, name="create_design"),
    path("quotations/<int:pk>/designs/", design_history, name="design_history"),
    path("orders/<int:pk>/payment/", payment_create, name="payment_create"),
    path("orders/<int:pk>/delivery/", delivery_update, name="delivery_update"),
    path("notifications/", manager_notifications, name="manager_notifications"),
    path("customers/", customer_list, name="customers"),
    path("customers/add/", customer_create, name="customer_create"),
    path("customers/<int:pk>/", customer_detail, name="customer_detail"),
    path("customers/<int:pk>/edit/", customer_edit, name="customer_edit"),
    path("customers/<int:pk>/interactions/add/", customer_interaction_create, name="customer_interaction_create"),
    path("enquiries/", enquiry_list, name="enquiries"),
    path("enquiries/add/", enquiry_create, name="enquiry_create"),
    path("enquiries/<int:pk>/edit/", enquiry_edit, name="enquiry_edit"),
    path("quotations/", quotation_list, name="quotations"),
    path("quotations/add/", quotation_create, name="quotation_create"),
    path("quotations/<int:pk>/", quotation_detail, name="quotation_detail"),
    path("quotations/<int:pk>/pdf/", quotation_pdf, name="quotation_pdf"),
    path("quotations/<int:pk>/edit/", quotation_edit, name="quotation_edit"),
    path("orders/", order_list, name="orders"),
    path("orders/add/", order_create, name="order_create"),
    path("orders/<int:pk>/", order_detail, name="order_detail"),
    path("orders/<int:pk>/pdf/", order_pdf, name="order_pdf"),
    path("orders/<int:pk>/edit/", order_edit, name="order_edit"),
]
